### ISSUE TITLE
Visibility of constants?

### ISSUE THREAD

**Issue by michalbundyra** [zendframework/zend-expressive-session#10]
As we require PHP 7.1 fot the library I think we should explicit defined class constant visibility.

This is new feature in PHP 7.1:
http://php.net/manual/en/migration71.new-features.php#migration71.new-features.class-constant-visibility

And here we have defined constant:
https://github.com/zendframework/zend-expressive-session/blob/master/src/SessionMiddleware.php#L17

Thoughts?

**Comment by froschdesign** [comment]
Sorry, I can not remove the wrong reaction / emoji!

The correct one: 👍
