### ISSUE TITLE
PhpSessionPersistence *NOT* shipped, documentation unclear

### ISSUE THREAD

**Issue by nclundsten** [zendframework/zend-expressive-session#20]
from [https://github.com/zendframework/zend-expressive-session#basic-usage](https://github.com/zendframework/zend-expressive-session#basic-usage)

reads:
> The default use case is to use the shipped PhpSessionPersistence adapter with the shipped SessionMiddleware. As such, you can pipe it to your application:

I'm getting:

> Zend \ ServiceManager \ Exception \ ServiceNotFoundException
Unable to resolve service "Zend\Expressive\Session\SessionPersistenceInterface" to a factory; are you certain you provided it during configuration?

Documentation regarding setup and use, lacks detail about needing a factory for `SessionPersistenceInterface` and since there are mentions of a custom/alternate persistence, it's confusing that the mentioned `PhpSessionPersistence`, and an accompanying factory are not included

did i just not get enough coffee this morning?

**EDIT:** AH, it looks like the documentation just needs to be updated.. 
i found [zendframework/zend-expressive-session-ext](https://github.com/zendframework/zend-expressive-session-ext) in `suggest`
assuming it was originally part of this package and was recently separated.

**Comment by weierophinney** [comment]
The `intro` page, where installation is covered, says this:

> However, the package is not immediately useful unless you have a persistence
> adapter. If you are okay with using ext-session, you can install the following
> package as well:
> 
> ```bash
> $ composer require zendframework/zend-expressive-session-ext
> ```

I'll import that information into the README file as well, however.

**Comment by weierophinney** [comment]
Fixed!
