### ISSUE TITLE
Regarding php support can we allow from php7.0 ? Latest debian still runs on php7.0

### ISSUE THREAD

**Issue by rimvislt** [zendframework/zend-expressive-session#25]
- [ x] I was not able to find an [open](https://github.com/zendframework/zend-expressive-session/issues?q=is%3Aopen) or [closed](https://github.com/zendframework/zend-expressive-session/issues?q=is%3Aclosed) issue matching what I'm seeing.
 - [ ] This is not a question. (Questions should be asked on [slack](https://zendframework.slack.com/) ([Signup for Slack here](https://zendframework-slack.herokuapp.com/)) or our [forums](https://discourse.zendframework.com/).)

Provide a narrative description of what you are trying to accomplish.

### Code to reproduce the issue

```php
```

**Comment by weierophinney** [comment]
No.

[We announced last year](https://framework.zend.com/blog/2017-06-06-zf-php-7-1.html) that all new packages would support PHP 7.1+, and any new major version of a package would support PHP 7.1+ as well.

This is done for several reasons:

- PHP 5.6 and 7.0 both reach EOL at the end of 2018
- We are trying to reduce the number of PHP versions we support, as the more versions we support, the more difficult it is to provide fixes that work across all versions.
- We want to use a number of new language features such as return type hints, scalar type hints, void return types, and nullable types, as they help provide consistency and predictability for end users.
